const data = [
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "08:00",
    horaFin: "09:00",
    total: 1,
    alumno: "Juanito Perez",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "09:00",
    horaFin: "10:00",
    total: 1,
    alumno: "Mariana Alvarado González",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "10:00",
    horaFin: "11:00",
    total: 1,
    alumno: "Juanito",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "10:00",
    horaFin: "11:00",
    total: 1,
    alumno: "Juanito",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
];

const clasesData = [
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    maestro: "Andres",
    alumno: "Juanito Perez",
    horaInicio: "08:00",
    horaFin: "09:00",
    total: 1,
    modalidad: "Presencial",
    apoyoGas: "200",
    comentarios: "Ninguno",
  },
  {
    fecha: "02/02/2021",
    dia: "Martes",
    maestro: "Maria Lopez",
    alumno: "Ana García",
    horaInicio: "10:00",
    horaFin: "11:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Uso de plataforma Zoom",
  },
  {
    fecha: "03/03/2021",
    dia: "Miércoles",
    maestro: "Carlos Ramirez",
    alumno: "Luis Fernández",
    horaInicio: "14:00",
    horaFin: "15:00",
    total: 1,
    modalidad: "Presencial",
    apoyoGas: "150",
    comentarios: "Revisión de tareas",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
];

export { data, clasesData };
