const data = [
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "08:00",
    horaFin: "09:00",
    total: 1,
    alumno: "Juanito Perez",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "09:00",
    horaFin: "10:00",
    total: 1,
    alumno: "Mariana Alvarado González",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "10:00",
    horaFin: "11:00",
    total: 1,
    alumno: "Juanito",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    horaInicio: "10:00",
    horaFin: "11:00",
    total: 1,
    alumno: "Juanito",
    modalidad: "Presencial",
    apoyoGas: "Si",
    comentarios: "Ninguno",
  },
];

const clasesData = [
  {
    fecha: "01/01/2021",
    dia: "Lunes",
    maestro: "Andres",
    alumno: "Juanito Perez",
    horaInicio: "08:00",
    horaFin: "09:00",
    total: 1,
    modalidad: "Presencial",
    apoyoGas: "200",
    comentarios: "Ninguno",
  },
  {
    fecha: "02/02/2021",
    dia: "Martes",
    maestro: "Maria Lopez",
    alumno: "Ana García",
    horaInicio: "10:00",
    horaFin: "11:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Uso de plataforma Zoom",
  },
  {
    fecha: "03/03/2021",
    dia: "Miércoles",
    maestro: "Carlos Ramirez",
    alumno: "Luis Fernández",
    horaInicio: "14:00",
    horaFin: "15:00",
    total: 1,
    modalidad: "Presencial",
    apoyoGas: "150",
    comentarios: "Revisión de tareas",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
  {
    fecha: "04/04/2021",
    dia: "Jueves",
    maestro: "Sofia Martinez",
    alumno: "Miguel Hernández",
    horaInicio: "09:00",
    horaFin: "10:30",
    total: 1.5,
    modalidad: "Online",
    apoyoGas: "0",
    comentarios: "Sesión grabada",
  },
];

const maestrosData = [
  {
    name: "Mariana Ampudia",
    clases: [
      {
        id: 234321,
        fecha: "12/08/2024",
        alumno: "Andres Cardenas",
        clase: "Matematicas",
        horas: 2,
        modalidad: "Presencial",
        apoyoGas: 100,
      },
      {
        id: 83831,
        fecha: "10/04/2024",
        alumno: "Patricia Pech",
        clase: "Español",
        horas: 1,
        modalidad: "Presencial",
        apoyoGas: 0,
      },
    ],
  },
  {
    name: "Ana Lopez",
    clases: [
      {
        id: 564321,
        fecha: "05/08/2024",
        alumno: "Juan Hernandez",
        clase: "Ciencias",
        horas: 2.5,
        modalidad: "En línea",
        apoyoGas: 0,
      },
      {
        id: 93831,
        fecha: "15/07/2024",
        alumno: "Luisa Torres",
        clase: "Ingles",
        horas: 1.5,
        modalidad: "Presencial",
        apoyoGas: 50,
      },
    ],
  },
  {
    name: "Claudia Fernandez",
    clases: [
      {
        id: 334721,
        fecha: "20/06/2024",
        alumno: "Santiago Garcia",
        clase: "Historia",
        horas: 1,
        modalidad: "En línea",
        apoyoGas: 0,
      },
      {
        id: 27831,
        fecha: "28/05/2024",
        alumno: "Valeria Martinez",
        clase: "Arte",
        horas: 2,
        modalidad: "Presencial",
        apoyoGas: 120,
      },
    ],
  },
  {
    name: "Laura Perez",
    clases: [
      {
        id: 987321,
        fecha: "02/07/2024",
        alumno: "Manuel Ortiz",
        clase: "Geografía",
        horas: 1.5,
        modalidad: "Presencial",
        apoyoGas: 70,
      },
      {
        id: 47831,
        fecha: "18/06/2024",
        alumno: "Juliana Castro",
        clase: "Biología",
        horas: 2.5,
        modalidad: "En línea",
        apoyoGas: 0,
      },
    ],
  },
  {
    name: "Laura Perez",
    clases: [
      {
        id: 987321,
        fecha: "02/07/2024",
        alumno: "Manuel Ortiz",
        clase: "Geografía",
        horas: 1.5,
        modalidad: "Presencial",
        apoyoGas: 70,
      },
      {
        id: 47831,
        fecha: "18/06/2024",
        alumno: "Juliana Castro",
        clase: "Biología",
        horas: 2.5,
        modalidad: "En línea",
        apoyoGas: 0,
      },
    ],
  },
];

const alumnosData = [
  {
    name: "Mara Vazquez",
    clases: {
      fecha: "1/01/2024",
      clase: "Matematicas",
      maestro: "Mariana Ampudia",
      horas: 1,
      modalidad: "Presencial",
    },
  },
  {
    name: "Carlos Gómez",
    clases: {
      fecha: "5/02/2024",
      clase: "Física",
      maestro: "Juan Pérez",
      horas: 2,
      modalidad: "Online",
    },
  },
  {
    name: "Lucía Fernández",
    clases: {
      fecha: "10/03/2024",
      clase: "Química",
      maestro: "Ana García",
      horas: 1.5,
      modalidad: "Presencial",
    },
  },
  {
    name: "Pedro Sánchez",
    clases: {
      fecha: "20/04/2024",
      clase: "Historia",
      maestro: "Ricardo Méndez",
      horas: 2,
      modalidad: "Online",
    },
  },
  {
    name: "Sofía Martínez",
    clases: {
      fecha: "25/05/2024",
      clase: "Inglés",
      maestro: "Laura Rodríguez",
      horas: 1,
      modalidad: "Presencial",
    },
  },
];

export { data, clasesData, maestrosData, alumnosData };
